stages:
  - build
  - deploy

variables:
  DBT_PROFILES_DIR: $CI_PROJECT_DIR/automate/dbt
  # DATACOVES__DBT_HOME: $CI_PROJECT_DIR/transform
  DATACOVES__DBT_HOME: $CI_PROJECT_DIR
  DATACOVES__MAIN__ACCOUNT: $DB_ACCOUNT
  DATACOVES__MAIN__SCHEMA: $DB_SCHEMA
  DATACOVES__MAIN__ROLE: $DB_ROLE
  DATACOVES__MAIN__WAREHOUSE: $DB_WAREHOUSE
  DATACOVES__MAIN__USER: $DB_USER
  DATACOVES__MAIN__PASSWORD: $DB_PASSWORD
  DATACOVES__TEST_DATABASE: $TEST_DATABASE
  DATACOVES__PROD_DATABASE: $PROD_DATABASE

build_and_test:
  image: datacoves/ci-basic-dbt-snowflake:2
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - cd $$CI_PROJECT_DIR
    - export DATACOVES__MAIN__DATABASE=$DATACOVES__TEST_DATABASE

  stage: build
  script:
    - git fetch origin main
    - git diff origin/main HEAD --name-status 
    - cd $DATACOVES__DBT_HOME
    - dbt deps
    - dbt build --fail-fast
    - cd $CI_PROJECT_DIR
    - CHANGED_FILES=$(git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME HEAD)
    - pre-commit run --files $CHANGED_FILES --config .pre-commit-config.yaml
  only:
    - merge_requests

generate_and_deploy_docs:
  stage: deploy
  before_script:
  - git config user.email $GITLAB_USER_EMAIL
  - git config user.name GITLAB_USER_NAME
  - project_url=$(echo $CI_PROJECT_URL | sed 's/https:\/\///')
  - git config pull.rebase false  
  - export DATACOVES__MAIN__DATABASE=$DATACOVES__PROD_DATABASE
  - echo $DATACOVES__MAIN__DATABASE
  image: datacoves/ci-basic-dbt-snowflake:2
  
  script:
    - cd $DATACOVES__DBT_HOME
    - dbt deps
    - dbt build
    - dbt docs generate
    - cp -r target/* $CI_PROJECT_DIR
    - git update-ref -d refs/heads/dbt-docs
    - git switch --orphan dbt-docs
    - cd $CI_PROJECT_DIR
    - git add catalog.json
    - git add graph.gpickle
    - git add index.html
    - git add manifest.json
    - git add run_results.json
    - git commit -m "Update dbt documentation"
    - git push --force https://oauth2:$GITLAB_PUSH_TOKEN@$project_url dbt-docs 

  only:
    - main
