stages:
  - build
  - deploy

variables:
  DBT_PROFILES_DIR: $CI_PROJECT_DIR/automate/dbt
  # DATACOVES__DBT_HOME: $CI_PROJECT_DIR/transform
  DATACOVES__DBT_HOME: $CI_PROJECT_DIR
  DATACOVES__MAIN__ACCOUNT: $DATACOVES_MAIN_ACCOUNT
  DATACOVES__MAIN__DATABASE: $DATACOVES_MAIN_DATABASE
  DATACOVES__MAIN__SCHEMA: $DATACOVES_MAIN_SCHEMA
  DATACOVES__MAIN__ROLE: $DATACOVES_MAIN_ROLE
  DATACOVES__MAIN__WAREHOUSE: $DATACOVES_MAIN_WAREHOUSE
  DATACOVES__MAIN__USER: $DATACOVES_MAIN_USER
  DATACOVES__MAIN__PASSWORD: $DATACOVES_MAIN_PASSWORD

default:
  image: datacoves/ci-basic-dbt-snowflake:2
  before_script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - cd $$CI_PROJECT_DIR

build_and_test:
  stage: build
  script:
    - git fetch origin main
    - git diff origin/main HEAD --name-status 
    - cd $DATACOVES__DBT_HOME
    - dbt deps
    - dbt build --fail-fast
    - cd $CI_PROJECT_DIR
    - CHANGED_FILES=$(git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME HEAD)
    - pre-commit run --files $CHANGED_FILES --config .pre-commit-config.yaml
  only:
    - merge_requests

generate_and_deploy_docs:
  stage: deploy
  before_script:
  - git config user.email $GITLAB_USER_EMAIL
  - git config user.name GITLAB_USER_NAME
  - project_url=$(echo $CI_PROJECT_URL | sed 's/https:\/\///')
  - git config pull.rebase false  
  image: datacoves/ci-basic-dbt-snowflake:2
  
  script:
    - git update-ref -d refs/heads/dbt-docs
    - git switch --orphan dbt-docs
    - cd $DATACOVES__DBT_HOME
    - ls
    - dbt deps
    - dbt build
    - dbt docs generate
    - cp -r target/* $CI_PROJECT_DIR
    - cd $CI_PROJECT_DIR
    - git add catalog.json
    - git add graph.gpickle
      git add index.html
    - git add manifest.json
    - git add run_results.json
    - git commit -m "Update dbt documentation"
    - git push https://oauth2:$GITLAB_PUSH_TOKEN@$project_url dbt-docs
  only:
    - main
