default:
  target: default_target
  outputs:
    default_target:
      type: redshift
      # host: "{{ env_var('DATACOVES__MAIN__HOST') }}"
      host: default.468004607141.us-west-2.redshift-serverless.amazonaws.com
      user: "{{ env_var('DATACOVES__MAIN__USER') }}"
      password: "{{ env_var('DATACOVES__MAIN__PASSWORD') }}"
      dbname: "{{ env_var('DATACOVES__MAIN__DATABASE') }}"
      schema: "{{ env_var('DATACOVES__MAIN__SCHEMA') }}"
      port: 5439
      threads: 8
      keepalives_idle: 240
      connect_timeout: 900
